[package]
name = "bitcoin-crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.2"
chrono = "0.4.38"
futures = "0.3.30"
rand = "0.8.5"
thiserror = "1.0.63"
tokio = { version = "1.34", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
